# Generated by Django 3.2.7 on 2021-11-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tibikon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saints',
            name='name',
            field=models.CharField(default='none', max_length=255, verbose_name='name'),
        ),
    ]
